### PR TITLE
Update index.astro

### PR DESCRIPTION
**Pull request by SSolarite**
added age

### CODE REVIEW

**Comment by metamethods** [comment]
@lukadev-0 you should merge this :trollface:

**Comment by lukadev-0** [comment]
no

**Comment by metamethods** [comment]
https://user-images.githubusercontent.com/96776358/233412479-4fca33b7-d9de-4a7c-a508-a82810a4ec2e.mp4

**Comment by SSolarite** [comment]
@lukadev-0 lgtm pls

**Comment by SSolarite** [comment]
MERGE.

**Comment by SSolarite** [comment]
MERGE THIS NOW.

**Pull request closed without merging**
